name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: 'lts'
      - uses: julia-actions/cache@v2
      - name: Load package
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); using KerrGeodesics'
